"""empty message

Revision ID: 0caaa7934266
Revises: 55c90afd4aa3
Create Date: 2022-07-18 18:49:52.312478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caaa7934266'
down_revision = '55c90afd4aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('work', 'term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('work', 'duration')
    # ### end Alembic commands ###
