"""empty message

Revision ID: 1589d7119887
Revises: be9ccd562b08
Create Date: 2022-08-12 10:15:11.560789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1589d7119887'
down_revision = 'be9ccd562b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'status')
    # ### end Alembic commands ###
