"""empty message

<<<<<<< HEAD:migrations/versions/7b0a026893b5_.py
<<<<<<<< HEAD:migrations/versions/0ef02123255e_.py
Revision ID: 0ef02123255e
Revises: 
Create Date: 2022-08-03 17:38:48.589490
========
Revision ID: 7b0a026893b5
Revises: 
Create Date: 2022-08-03 14:37:59.781456
>>>>>>>> 7d0fb88f5f1d2a5487b77c816c46e693acb73208:migrations/versions/7b0a026893b5_.py
=======
Revision ID: 1ecf8af0704c
Revises: 
Create Date: 2022-08-06 13:42:52.173899
>>>>>>> 1515d13f2ecf2f257255cc0f88917eae7a52e3aa:migrations/versions/1ecf8af0704c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/7b0a026893b5_.py
<<<<<<<< HEAD:migrations/versions/0ef02123255e_.py
revision = '0ef02123255e'
========
revision = '7b0a026893b5'
>>>>>>>> 7d0fb88f5f1d2a5487b77c816c46e693acb73208:migrations/versions/7b0a026893b5_.py
=======
revision = '1ecf8af0704c'
>>>>>>> 1515d13f2ecf2f257255cc0f88917eae7a52e3aa:migrations/versions/1ecf8af0704c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('worker_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('cif', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_signup_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_signup_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('budget')
    op.drop_table('work')
    op.drop_table('login')
    op.drop_table('worker_signup')
    op.drop_table('user_signup')
    # ### end Alembic commands ###
