"""empty message

<<<<<<<< HEAD:migrations/versions/73f97ed73cd4_.py
Revision ID: 73f97ed73cd4
Revises: 
Create Date: 2022-07-29 18:34:58.179428
========
Revision ID: 250c9f9846e6
Revises: 
Create Date: 2022-07-29 16:33:44.931335
>>>>>>>> 72caad378ea5d37807c97c58c509a449e9978bce:migrations/versions/250c9f9846e6_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/73f97ed73cd4_.py
revision = '73f97ed73cd4'
========
revision = '250c9f9846e6'
>>>>>>>> 72caad378ea5d37807c97c58c509a449e9978bce:migrations/versions/250c9f9846e6_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('worker_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('cif', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_signup_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_signup_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    op.drop_table('work')
    op.drop_table('ratings')
    op.drop_table('login')
    op.drop_table('worker_signup')
    op.drop_table('user_signup')
    # ### end Alembic commands ###
