"""empty message

Revision ID: 2fa25c1d35df
Revises: 5dcdd1c83a0b
Create Date: 2022-07-12 16:42:46.759242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa25c1d35df'
down_revision = '5dcdd1c83a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'password',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user_signup', 'password',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_signup', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('login', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
