"""empty message

<<<<<<<< HEAD:migrations/versions/5a090b1fd598_.py
Revision ID: 5a090b1fd598
Revises: 
Create Date: 2022-08-09 12:53:59.170695
========
Revision ID: 196db2ecf79b
Revises: 
Create Date: 2022-08-08 16:32:20.383960
>>>>>>>> 29090470bdfc3416e52003760e3a69cc5bd0e593:migrations/versions/196db2ecf79b_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/5a090b1fd598_.py
revision = '5a090b1fd598'
========
revision = '196db2ecf79b'
>>>>>>>> 29090470bdfc3416e52003760e3a69cc5bd0e593:migrations/versions/196db2ecf79b_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('worker_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('cif', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_signup_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_signup_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('budget')
    op.drop_table('work')
    op.drop_table('login')
    op.drop_table('worker_signup')
    op.drop_table('user_signup')
    # ### end Alembic commands ###
