"""empty message

Revision ID: 5cc1b620ff76
Revises: fa91f2f2e618
Create Date: 2022-08-03 08:45:54.392763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc1b620ff76'
down_revision = 'fa91f2f2e618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.add_column('worker_signup', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_signup', 'description')
    op.alter_column('budget', 'duration',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
