"""empty message

Revision ID: 5dcdd1c83a0b
Revises: 25cc2d0f5894
Create Date: 2022-07-12 16:33:26.347040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcdd1c83a0b'
down_revision = '25cc2d0f5894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_signup', 'password',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_signup', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
