"""empty message

Revision ID: 654b88b6495b
Revises: 969e4831a3a9
Create Date: 2022-09-15 09:27:24.728224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654b88b6495b'
down_revision = '969e4831a3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_signup', 'postcode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('worker_signup', 'postcode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_signup', 'postcode',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_signup', 'postcode',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
