"""empty message

Revision ID: 70c91eb5d8ce
Revises: c3bc160b6a5b
Create Date: 2022-07-07 21:09:07.834650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c91eb5d8ce'
down_revision = 'c3bc160b6a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('worker_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tlf_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('cif', sa.Integer(), nullable=True),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_number')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('pictures', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_signup.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    op.drop_table('ratings')
    op.drop_table('worker_signup')
    op.drop_table('user_signup')
    op.drop_table('login')
    # ### end Alembic commands ###
