"""empty message

Revision ID: a8ab9eb5367f
Revises: 4b61ee0ec8e0
Create Date: 2022-07-20 15:55:33.479084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ab9eb5367f'
down_revision = '4b61ee0ec8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work', 'location',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work', 'location',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
