"""empty message

Revision ID: ce74f2f89ac2
Revises: 305f6d034371
Create Date: 2022-07-14 19:08:27.592134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce74f2f89ac2'
down_revision = '305f6d034371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_signup', sa.Column('sector', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_signup', 'sector')
    # ### end Alembic commands ###
