"""empty message

Revision ID: d8de92bb3922
Revises: e1fbda0f1942
Create Date: 2022-07-14 21:03:12.047218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8de92bb3922'
down_revision = 'e1fbda0f1942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
