"""empty message

Revision ID: e1fbda0f1942
Revises: ce74f2f89ac2
Create Date: 2022-07-14 21:02:03.336583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fbda0f1942'
down_revision = 'ce74f2f89ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('sector', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'sector')
    # ### end Alembic commands ###
